<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //에러 핸들링
        //try 블럭안에 에러가 발생하면 catch에서 에러를 처리하기 때문에
        //스크립트는 죽지 않음.
        // '{"age" : 30}' ''안에 ""
        let json = '{"age" : 30}';
        try{
            //json 타입을 object로 변환
            let user = JSON.parse(json);
            
            if(!user.name){
                throw new SyntaxError("이름이 없음");
            }
           
        }
        //에러가 발생하지 않으면 무시됨
       //try catch를 쓰면 에러발생시에 스크립트를 막지않음 우와 쉬는시간이다
        catch(e){
            alert(e.message);
            //에러가 발생하던 말던 트라이 캐치가 끝나면 finally로 실행시킬수있음
        } finally{
            console.log("마지막 실행");

        }
        console.log('실행');
    </script>
</body>
</html>